/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PE_Cnvrt.c
**     Project     : Comunicacion_Serial
**     Processor   : MC9S08QE128CLK
**     Component   : PE_Cnvrt
**     Version     : Driver 01.17
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2018-04-04, 15:56, # CodeGen: 40
**     Abstract    :
**         This component "PE_Cnvrt" implements internal methods and definitions
**         used by components working with converters.
**     Settings    :
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PE_Cnvrt.c
** @version 01.17
** @brief
**         This component "PE_Cnvrt" implements internal methods and definitions
**         used by components working with converters.
*/         
/*!
**  @addtogroup PE_Cnvrt_module PE_Cnvrt module documentation
**  @{
*/         

#include "PE_Cnvrt.h"
#include "IO_Map.h"


#define PE_Cnvrt_NumChan  3U

static volatile PE_Cnvrt_ChanMaskType PE_Cnvrt_EnChan; /* Enable/Disable mask of channels */
static volatile PE_Cnvrt_ChanMaskType PE_Cnvrt_EnChanFlags; /* Flags indicating that a particular channel has been read. */
static volatile bool PE_Cnvrt_CnvLck;            /* Lock/Unlock of AD converter (sharing problem)*/
static byte PE_Cnvrt_ChSpee[PE_Cnvrt_NumChan];   /* Speed of channels */
static const byte PE_Cnvrt_ChCode[PE_Cnvrt_NumChan] = { 0x40U, 0x41U, 0x48U}; /* Codes of channels */
static volatile PE_Cnvrt_ChanMaskType PE_Cnvrt_ChRun; /* Index of channel in converting proces */
static volatile byte PE_Cnvrt_Mux;               /* Settings of ADC multiplexer */
static TProc PE_Cnvrt_ChPro[3];                  /* Interrupt procedures of each channel */
volatile word PE_Cnvrt_ADResults[PE_Cnvrt_NumChan]; /* Array of A/D results */

/*
** ===================================================================
**     Method      :  PE_Cnvrt_PE_CnvrtPE_Init (component PE_Cnvrt)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_Cnvrt_Init(void)
{
  PE_Cnvrt_EnChan = 0U;
  PE_Cnvrt_EnChanFlags = 0U;
  PE_Cnvrt_CnvLck = 0U;
  PE_Cnvrt_Mux = 0U;
  PE_Cnvrt_ChRun = 0U;
}

/*
** ===================================================================
**     Method      :  PE_Cnvrt_InterruptInternal (component PE_Cnvrt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         .
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_Cnvrt_InterruptInternal(void)
{
  PE_Cnvrt_ChanMaskType localEnChanFlags;

  if (!PE_Cnvrt_CnvLck) {
    if (PE_Cnvrt_EnChan != 0U) {       /* Is conversion of a channel enabled? */
      if (PE_Cnvrt_ChRun != 0U) {
/*lint -save  -e926 -e927 -e928 -e929 Disable MISRA rule (11.4) checking. */
        ((TWREG*)(&PE_Cnvrt_ADResults[PE_Cnvrt_Mux]))->b.high = ADCRH; /* Save measured value */
        ((TWREG*)(&PE_Cnvrt_ADResults[PE_Cnvrt_Mux]))->b.low = ADCRL; /* Save measured value */
/*lint -restore Enable MISRA rule (11.4) checking. */
/*lint -save  -e740 -e931 Disable MISRA rule (1.2) checking. */
        PE_Cnvrt_EnChanFlags |= PE_Cnvrt_ChRun; /* Store info which channel has been read */
/*lint -restore Enable MISRA rule (1.2) checking. */
      } else {
        PE_Cnvrt_ChRun = 1U;           /* Start measurement from the first channel */
      }
      localEnChanFlags = PE_Cnvrt_EnChanFlags;
      localEnChanFlags &= PE_Cnvrt_EnChan;
      if (localEnChanFlags == PE_Cnvrt_EnChan) { /* Have all required channels been read? */
        PE_Cnvrt_EnChanFlags = 0U;     /* Reset the "has been read" flags */
        PE_Cnvrt_ChPro[0]();           /* Execute the interrupt routine */
        PE_Cnvrt_ChPro[1]();           /* Execute the interrupt routine */
        PE_Cnvrt_ChPro[2]();           /* Execute the interrupt routine */
      }
      if (PE_Cnvrt_EnChan != 0U) {     /* Is conversion of a channel enabled? */
        do {
          PE_Cnvrt_ChRun = (PE_Cnvrt_ChanMaskType)((PE_Cnvrt_ChanMaskType)PE_Cnvrt_ChRun << 1U); /* Select the next channel in the list */
          if (++PE_Cnvrt_Mux == PE_Cnvrt_NumChan) { /* Is the next channel index out of range? */
            PE_Cnvrt_Mux = 0U;         /* Reset the channel index */
            PE_Cnvrt_ChRun = 1U;       /* Reset the channel selection mask */
          }
/*lint -save  -e740 -e931 Disable MISRA rule (1.2) checking. */
        } while ((PE_Cnvrt_ChRun & PE_Cnvrt_EnChan) == 0U);
/*lint -restore Enable MISRA rule (1.2) checking. */
      }
    }
  }
  if (PE_Cnvrt_EnChan != 0U) {
    ADCCFG = PE_Cnvrt_ChSpee[PE_Cnvrt_Mux]; /* Enable device, set result mode and prescaler bits */
    ADCSC1 = PE_Cnvrt_ChCode[PE_Cnvrt_Mux]; /* Enable interrupt, set channel (start measurement) */
  } else {
    ADCSC1 = 0x1FU;                    /* Stop the device */
  }
}

/*
** ===================================================================
**     Method      :  PE_Cnvrt_SetSpe (component PE_Cnvrt)
**
**     Description :
**         The method stores the configuration of the AD converter for 
**         the specified channel.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_Cnvrt_SetSpe(byte Index, byte NewSpe)
{
  PE_Cnvrt_CnvLck++;
  PE_Cnvrt_ChSpee[Index] = NewSpe;
  PE_Cnvrt_CnvLck--;
}

/*
** ===================================================================
**     Method      :  PE_Cnvrt_SetPro (component PE_Cnvrt)
**
**     Description :
**         The method stores the pointer to the service routine for 
**         specified channel.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_Cnvrt_SetPro(byte Index, TProc Proc)
{
  PE_Cnvrt_CnvLck++;
  PE_Cnvrt_ChPro[Index] = Proc;
  PE_Cnvrt_CnvLck--;
}

/*
** ===================================================================
**     Method      :  PE_Cnvrt_RunSta (component PE_Cnvrt)
**
**     Description :
**         The method enables measurement of channels given by a mask.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_Cnvrt_RunSta(PE_Cnvrt_ChanMaskType Mask)
{
  PE_Cnvrt_CnvLck++;
  PE_Cnvrt_EnChan |= Mask;             /* Conversion of channels specified by the mask is enabled */
  PE_Cnvrt_EnChanFlags &= (PE_Cnvrt_ChanMaskType)(~(PE_Cnvrt_ChanMaskType)Mask); /* Clear flags indication that a specific channels has been converted */
  PE_Cnvrt_CnvLck--;
  if (PE_Cnvrt_ChRun == 0U) {
    PE_Cnvrt_InterruptInternal();
  }
}

/*
** ===================================================================
**     Method      :  PE_Cnvrt_RunSto (component PE_Cnvrt)
**
**     Description :
**         The method disables measurement of channels given by a mask.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_Cnvrt_RunSto(PE_Cnvrt_ChanMaskType Mask)
{
  PE_Cnvrt_CnvLck++;
  PE_Cnvrt_EnChan &= (PE_Cnvrt_ChanMaskType)(~(PE_Cnvrt_ChanMaskType)Mask);
  if (PE_Cnvrt_EnChan == 0U) {
    ADCSC1 = 0x1FU;
    (void) ADCRL;
    PE_Cnvrt_ChRun = 0U;               /* Indicate that there is no channel in measurement */
    PE_Cnvrt_Mux = 0U;                 /* Reset the channel index */
  }
  PE_Cnvrt_CnvLck--;
}

/*
** ===================================================================
**     Method      :  PE_Cnvrt_PE_CnvrtInterrupt (component PE_Cnvrt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         .
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(PE_Cnvrt_Interrupt)
{
  PE_Cnvrt_InterruptInternal();
}

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
