/*
** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PE_Cnvrt.inc
**     Project     : Comunicacion_Serial
**     Processor   : MC9S08QE128CLK
**     Component   : PE_Cnvrt
**     Version     : Driver 01.17
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2018-04-04, 14:48, # CodeGen: 36
**     Abstract    :
**         This component "PE_Cnvrt" implements internal methods and definitions
**         used by components working with converters.
**     Settings    :
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################
*/

#ifndef __PE_Cnvrt
#define __PE_Cnvrt

/* MODULE PE_Cnvrt. */
#include "PE_Types.h"


/* Internal method prototypes */

void PE_Cnvrt_InterruptInternal(void);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_InterruptInternal (component PE_Cnvrt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         .
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

typedef void (*TProc)(void);

typedef byte PE_Cnvrt_ChanMaskType;    /* Type used to define channel mask */

void PE_Cnvrt_Init(void);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_PE_CnvrtPE_Init (component PE_Cnvrt)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void PE_Cnvrt_Interrupt(void);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_PE_CnvrtInterrupt (component PE_Cnvrt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         .
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void PE_Cnvrt_SetSpe(byte Index, byte NewSpe);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_SetSpe (component PE_Cnvrt)
**
**     Description :
**         The method stores the configuration of the AD converter for 
**         the specified channel.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void PE_Cnvrt_SetPro(byte Index, TProc Proc);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_SetPro (component PE_Cnvrt)
**
**     Description :
**         The method stores the pointer to the service routine for 
**         specified channel.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void PE_Cnvrt_RunSta(PE_Cnvrt_ChanMaskType Mask);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_RunSta (component PE_Cnvrt)
**
**     Description :
**         The method enables measurement of channels given by a mask.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void PE_Cnvrt_RunSto(PE_Cnvrt_ChanMaskType Mask);
/*
** ===================================================================
**     Method      :  PE_Cnvrt_RunSto (component PE_Cnvrt)
**
**     Description :
**         The method disables measurement of channels given by a mask.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/


/* END PE_Cnvrt. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
#endif /* ifndef __PE_Cnvrt */
